### ISSUE TITLE
Get product catalog list

### ISSUE THREAD

**Issue by fjborquez** [fjborquez/katara-back#20]
| 8 | Get product catalog list | a product catalog list | product catalog process is triggered | a product catalog list with product type + product presentation will be generated.

**Comment by Norbbs** [comment]
@fjborquez la respuesta del endpoint trae información redundante como el category_id, brand_id, type_id y presentation_id
Ejemplo (marco con *):
{
      "id": 344,
      * "category_id": 9,
      * "brand_id": 50,
      * "type_id": 97,
      * "presentation_id": 108,
      "created_at": "2024-12-10T23:34:36.000000Z",
      "updated_at": null,
      "category": {
        "id": 9,
        "name": "Sauces and Dressings",
        "created_at": "2024-09-06T02:43:45.000000Z",
        "updated_at": null
      },
      "brand": {
        "id": 50,
        "name": "Malloa",
        "description": "Quality, flavor, and variety in tomato sauces.",
        "created_at": "2024-12-10T23:33:53.000000Z",
        "updated_at": null
      },
      "type": {
        "id": 97,
        "description": "Salsa de tomates",
        "created_at": "2024-09-06T02:43:06.000000Z",
        "updated_at": null
      },
      "presentation": {
        "id": 108,
        "description": "italiana",
        "created_at": "2024-12-10T23:31:08.000000Z",
        "updated_at": null
      }
    }
Además hay campos que no aportan valor a la pantalla que se va a construir.

Te dejo esta propuesta de objeto sin atributos redundantes y con lo que necesita la pantalla.
{
      "id": 344,
      "category": {
        "id": 9,
        "name": "Sauces and Dressings",
      },
      "brand": {
        "id": 50,
        "name": "Malloa",
      },
      "type": {
        "id": 97,
        "description": "Salsa de tomates",
      },
      "presentation": {
        "id": 108,
        "description": "italiana",
      }
}

**Comment by fjborquez** [comment]
Por ahora no es problema porque no impide que se cree la pantalla.
Más adelante no será problema porque a la API se le indicará que cambios exponer.
